# docker-compose file for my web site
version: '2'

services:

  nginx-proxy:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - personal-website
    mem_limit: 64m
    volumes:
      - ~/ssl:/etc/ssl

  personal-website:
    build: ./web
    mem_limit: 64m
    volumes:
      - ~/public_html:/usr/share/nginx/html
