# docker-compose file for my web site
version: '2'

services:

  nginx-proxy:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - personal-website
      - webdav-server
    mem_limit: 64m
    # command: sleep 3600
    volumes:
      - ~/ssl:/etc/ssl
    environment:
      - DEFAULT_SERVER_NAME
      - PRIMARY_SERVER_NAME
      - SECURE_SERVER_NAME

  personal-website:
    build: ./web
    mem_limit: 64m
    volumes:
      - ~/public_html:/srv
      
  webdav-server:
    build: ./webdav
    mem_limit: 64m
    volumes:
      - ~/webdav:/srv
    environment:
      - READWRITE=true
      - WEBDAV_USERNAME
      - WEBDAV_PASSWORD
