version: "2"

services:
  caddy-gen:
    container_name: caddy-gen
    image: "wemakeservices/caddy-gen:latest"
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs/acme:/etc/caddy/acme
      - ./certs/ocsp:/etc/caddy/ocsp
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - vscode
      - personal-website
      - webdav-server

  personal-website:
    build: ./web
    mem_limit: 64m
    volumes:
      - ~/public_html:/srv
    labels:
      - "virtual.host=patrick.wagstrom.net"
      - "virtual.alias=wagstrom.net www.wagstrom.net"
      - "virtual.port=80"
      - "virtual.tls-email=patrick@wagstrom.net"
      - "virtual.websockets"

  webdav-server:
    build: ./webdav
    mem_limit: 64m
    volumes:
      - ~/webdav:/srv
    environment:
      - READWRITE=true
    env_file:
      - .env
    labels:
      - "virtual.host=secure.wagstrom.net"
      - "virtual.port=80"
      - "virtual.tls-email=patrick@wagstrom.net"
      - "virtual.websockets"

  vscode:
    image: codercom/code-server:v2
    volumes:
      - ~/.local/share/code-server:/home/coder/.local/share/code-server
      - ~:/home/coder/projects
    labels:
      - "virtual.host=vscode.wagstrom.com"
      # # - "virtual.alias=ww.myapp.com"
      - "virtual.port=8080"
      - "virtual.tls-email=patrick@wagstrom.net"
      - "virtual.websockets"
    env_file:
      - .env
